name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t juice-shop .
      - name: Run the Anchore Grype scan action
        uses: anchore/scan-action@v3
        with:
          image: 'juice-shop'
          fail-build: true
          severity-cutoff: critical
      - name: Scan the image and upload dependency results
        uses: anchore/sbom-action@v0
        with:
          image: 'juice-shop'
          artifact-name: image.spdx.json
          dependency-snapshot: true
  Sast-scan:
    name: semgrep
    runs-on: ubuntu-20.04
    container: returntocorp/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semgrep
        run: semgrep ci --config=auto --sarif  --output=semgrep.sarif||true
      - name: Upload Sarif file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'semgrep.sarif'
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
